DROP DATABASE AVALIACAO3M;
CREATE DATABASE AVALIACAO3M;

USE AVALIACAO3M;

CREATE TABLE SERVICO
(ID_SERVICO BIGINT PRIMARY KEY AUTO_INCREMENT,
TX_DESCRICAO VARCHAR(255) NOT NULL,
TX_TIPO VARCHAR(40) NOT NULL,
TX_UNIDADE VARCHAR(40) NOT NULL,
TX_PRECO DOUBLE NOT NULL);

select * from SERVICO;